# Generated by Django 2.0.2 on 2018-12-29 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('recever_name', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 't_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfirmedString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='用户注册时生成的验证码')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='验证码生成的时间')),
            ],
            options={
                'db_table': 't_confirmedString',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='用户的注册时间')),
                ('has_confirmed', models.BooleanField(default=False, verbose_name='用户是否激活')),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.AddField(
            model_name='confirmedstring',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test1.TUser', verbose_name='关联的用户'),
        ),
    ]
